### ISSUE TITLE
BUG: New Tenant

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#71]
Ever since this [commit](https://gitlab.com/notch8/adventist-dl/-/commit/edafd85f76275d65e87c80201e4e65baec509f68), a user is unable to create a new tenant without causing a 500 error, locally and in staging.

# ref: 
https://notch8.slack.com/archives/CQK3DBHAR/p1643668927495469

# Acceptance Criteria
- [ ] A user should be able to create a new tenant

documentation for cert:
Adventist notes:
- https://aws.amazon.com/blogs/security/tls-enabled-kubernetes-clusters-with-acm-private-ca-and-amazon-eks-2/
- https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/
- https://us-east-1.console.aws.amazon.com/ec2/v2/home?region=us-east-1#LoadBalancers:sort=loadBalancerName

**Comment by DiemBTran** [comment]
Related MRs:

[fix new account creation with sidekiq queue splitting](https://gitlab.com/notch8/adventist-dl/-/merge_requests/164)
!164
[Site specs](https://gitlab.com/notch8/adventist-dl/-/merge_requests/165)
!165
[udpate readme with new tenant create ingress requirements](https://gitlab.com/notch8/adventist-dl/-/merge_requests/181)
!181
[add-test-tenant-url-to-ingress-and-tls-for-client-verification](https://gitlab.com/notch8/adventist-dl/-/merge_requests/190)
!190

**Comment by DiemBTran** [comment]
Rob Feb 2022:

---

should be resolved by both [!165 (merged)](https://github.com/notch8/adventist-dl/-/merge_requests/165) and [!164 (merged)](https://github.com/notch8/adventist-dl/-/merge_requests/164)

**Comment by DiemBTran** [comment]
Diem March 2022

---

**Needs further review:**

**Summary:** Was able to create a tenant (https://118-test.s2.adventistdigitallibrary.org/), but cannot access it (`This site can’t be reached 118-test.s2.adventistdigitallibrary.org’s server IP address could not be found.`). There is no [Sentry](https://sentry.notch8.com/sentry/adventist/) error. Is that an issue related to the ticket?


**Details:** 

**Was able to create tenant: https://118-test.s2.adventistdigitallibrary.org/** 

---
![Image](https://user-images.githubusercontent.com/29311858/200079536-4a4a2b02-3faf-4eab-a1b1-29ea5b8b185f.png)

Cannot access it-- This site can’t be reached 118-test.s2.adventistdigitallibrary.org’s server IP address could not be found

---

![Image](https://user-images.githubusercontent.com/29311858/200079630-61fe8e45-1529-409f-8cb9-fcb6e4a07891.png)

no [Sentry](https://sentry.notch8.com/sentry/adventist/) error

---

![Image](https://user-images.githubusercontent.com/29311858/200079678-8749bfbb-a7fd-45ab-943e-f9a16cc6e1ca.png)

**Comment by DiemBTran** [comment]
Lea Ann May 2022

---

The tenants are created but an SSL cert needs to be generated for the domain. Software Services does not have access to dns server so any ssl certs need to be per specific domain. If a new tenant needs to be created, it will require a developer to update the ingress settings for that specific domain before the tenant is created.

---

April May 2022

---
SSL cert && nginx ingress

---
Lea Ann June 2022

---
To be clear, new tenants can be created successfully. They cannot be accessed until and SSL cert is generated. If a new tenant is to be created, a ticket to add SSL cert should be created for this work

**Comment by DiemBTran** [comment]
Katharine Van Arsdale July 2022

---
I'd like to test and verify this ticket, but I need to confirm the steps to create a new tenant. Can someone give me those steps? I need a reminder, since this process hasn't worked so I haven't tried it in a long time. Once I have some instructions, I understand that I can do most of the process within our instance of Hyku, with the exception of the final step, which requires me to create an SSL certification ticket every time I try to generate a new tenant.

**Comment by DiemBTran** [comment]
April Rieger - July 2022

---

Hi @KatharineV ! I went ahead and made a pdf with screenshots of how to test tenant creation here for you attached below.
[adventist-create-new-tenant-instructions.pdf](https://github.com/scientist-softserv/adventist-dl/files/9942211/adventist-create-new-tenant-instructions.pdf)

I went through the process of adding the new tenant to the values file in order to generate an ssl cert and ingress.

There is one more additional step, we either need to add a wildcard cert for https://s2.adventistdigitallibrary.org & https://b2.adventistdigitallibrary.org and the process will stay the same where anytime a tenant is created we would need to intervene on our end and add any subsequent tenants to the values file.

There is an alternate route that we can pursue but we would need cert-manager access to your DNS(AWS Route 53), cert-manager needs to be able to add records to Route53 in order to solve the DNS01 challenge in order to create an SSL cert dynamically. Here are a set of instructions to follow in doing so: https://cert-manager.io/docs/configuration/acme/dns01/route53/

Please let me know if you have any additional questions or need any additional information.

Thank you

**Comment by DiemBTran** [comment]
Katharine Van Arsdale - August 2022

---

Just chiming in to add that the ADL team discussed automatic SSL certifications, and this is the route we want to go if possible. Thanks, Eric, for collaborating with Software Services to set up our system to generate new tenants without human intervention! Software Services folks, if we run into any snags pursuing this route the way we have things set up, let us know.

**Comment by DiemBTran** [comment]
April R - Sept 2022

---

Thank you! Just getting back to this now.

**Comment by DiemBTran** [comment]
Katharine Van Arsdale - Oct 2022

---

Hey folks, we'd like to create a new tenant on staging and development. Is this ticket situation resolved to the point where we can do that and create new tenants in both locations? Thanks!!

![Image](https://user-images.githubusercontent.com/29311858/200081486-fcca85c4-a0ce-4fc0-9214-d0b089a815a2.png)



Update to say that I was able to create a tenant in S2, but it isn't accessible, as you can see in the screenshot error message. I can't test creating a tenant in B2 because my user account lacks proper credentials. So it seems like we've got a couple issues here: did we solve the SSL cert issue on the ADL side as you asked? And should I be using a different account to create new tenants on B2? If not, then I need help to grant my username the proper access. Thanks!

**Comment by KatharineV** [comment]
Hi team! I'd like to mark this ticket as the next top priority, after full text search, the Universal Viewer, and CSV/OAI import bugs are resolved.

**Comment by ShanaLMoore** [comment]
https://assaydepot.slack.com/archives/G0311DN2YCA/p1627684794017500

**Comment by ShanaLMoore** [comment]
**NOTE**: Katharine's desire is to have this completed by her board meeting (April 11th).

**Comment by ShanaLMoore** [comment]
After deploying, we tried to make a tenant called 'demo'. We still receive a 500 error: 



![Image](https://user-images.githubusercontent.com/10081604/230509289-149ed35a-e279-4d85-88c2-dd81bf906145.png)

The logs aren't very descriptive though and we aren't seeing anything from sentry. 

```
I, [2023-04-06T23:06:56.789464 #1] INFO -- : [b8f27878a026453827efda0689e83886] Completed 500 Internal Server Error in 3857ms (ActiveRecord: 2426.5ms) 
```

**Comment by ShanaLMoore** [comment]
removing the need rework label. I misunderstood what Rob meant by the description of his PR.

```
Note you will still need to add the tenant URL to the ingress section in ops/staging-deploy.tmpl.yaml or ops/production-deploy.tmpl.yaml as we do not have the ability to issue wildcard certs. the actual name (acme.b2.adventistdigitallibrary.org for example) has to be in the ops/production-deploy.tmpl.yaml and then deployed for it to work.
``` 

It sounds like if we want a new tenant there will need to be a process vs creating them on the fly. 

The process is adding their urls to the [ingress section](https://github.com/scientist-softserv/adventist-dl/blob/d82b41bbee54bcdedeca095e8bf4d83e2ccd203a/ops/production-deploy.tmpl.yaml#L40-L53) of the env's tmp.yml files

**Comment by kirkkwang** [comment]
After deploy I still cannot create a new tenant, moving this ticket back for now

**Comment by orangewolf** [comment]
in the end there were two issues here. 1 a setting missing on Adventist Dev Template. and 2 a complex dance to get wildcard dns set up and ssl certs issued.

**Comment by aprilrieger** [comment]
Testing this ticket for the DNS issue we were trying to resolve on TT6. I see that I am able to create a tenant. I am able to navigate to the tenant and see it is active without needing to add any additional hosts to the ingress. I see a cert that covers the tenant that is active. 

However, as a proprietor, when I create a new tenant I do receive a rails error page after adding a tenant short name and clicking save.

When trying to create a collection or work or anything in that tenant, you get errors. After navigating to the manage tenant page form the proprietor account you can see that the solr url is not correct: `http://127.0.0.1:8983/solr/b4d4ff82-f92b-48a4-9b95-2d074e0fb2d9` the `http://127.0.0.1:8983/` part should be pointed to the clusters solr url.

Here are the sentry error log captured with the error: https://scientist-inc.sentry.io/issues/3984997772/?project=6745020&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

![Image](https://github.com/scientist-softserv/adventist-dl/assets/63515648/afb5becb-0501-43e0-bf0f-98dad7a355b1)
![Image](https://github.com/scientist-softserv/adventist-dl/assets/63515648/10d29acb-f863-4b06-9f28-530bf590543a)
![Image](https://github.com/scientist-softserv/adventist-dl/assets/63515648/f906a15e-517e-45cc-9706-83c616a48ca5)
![Image](https://github.com/scientist-softserv/adventist-dl/assets/63515648/afd6024a-fb06-406e-8b47-709fcfae806d)

**Comment by aprilrieger** [comment]
Testing this ticket after deploying again made it all work. 
This is ready for client testing.

**Comment by KatharineV** [comment]
I tested on staging and created a new tenant, which I can view: https://wau.s2.adventistdigitallibrary.org/ 

It works! Thank you.
